package com.gamingevents.service;
import com.gamingevents.dto.AuthDtos.*; import com.gamingevents.entity.*; import com.gamingevents.repository.*; import com.gamingevents.security.JwtService;
import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
@Service public class AuthService { final UserRepository users; final PlayerProfileRepository profiles; final PasswordEncoder encoder; final JwtService jwt;
 public AuthService(UserRepository u,PlayerProfileRepository p,PasswordEncoder e,JwtService j){users=u;profiles=p;encoder=e;jwt=j;}
 @Transactional public TokenResponse register(RegisterRequest r){String email=r.email().trim().toLowerCase();if(users.findByEmail(email).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Email already registered");if(r.role()==Role.ADMIN)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Admin registration is not allowed"); User u=new User();u.setName(r.name().trim());u.setEmail(email);u.setPassword(encoder.encode(r.password()));u.setRole(r.role());users.save(u);if(u.getRole()==Role.PLAYER){PlayerProfile p=new PlayerProfile();p.setUser(u);p.setUsername(r.username()==null||r.username().isBlank()?email.split("@")[0]:r.username().trim());profiles.save(p);}return token(u);}
 public TokenResponse login(LoginRequest r){var u=users.findByEmail(r.email().trim().toLowerCase()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid email or password"));if(!u.isEnabled()||!encoder.matches(r.password(),u.getPassword()))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid email or password");return token(u);}
 public CurrentUserResponse current(String email){var u=users.findByEmail(email).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Authentication required"));return new CurrentUserResponse(u.getId(),u.getName(),u.getEmail(),u.getRole().name());}
 private TokenResponse token(User u){return new TokenResponse(jwt.create(u.getEmail(),u.getRole()),"Bearer",jwt.expirationSeconds(),u.getRole().name(),u.getName(),u.getEmail());}}
