-- V4: Game Catalog for Player Discovery
CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    icon_url VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

INSERT INTO games (name, description, icon_url, status) VALUES
('Valorant', '5v5 character-based tactical FPS where precise gunplay meets unique agent abilities.', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=60', 'ACTIVE'),
('CS2', 'Next era of legendary tactical FPS with dynamic smoke and sub-tick precision.', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=60', 'ACTIVE'),
('eFootball', 'Realistic digital football experience featuring world clubs and competitive divisions.', 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&auto=format&fit=crop&q=60', 'ACTIVE'),
('FIFA', 'World-class association football tournaments and competitive ultimate leagues.', 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=60', 'ACTIVE'),
('PUBG', 'Battle royale shooter where 100 players fight for survival across vast tactical maps.', 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&auto=format&fit=crop&q=60', 'ACTIVE'),
('Mobile Legends', '5v5 MOBA showdown on mobile featuring legendary heroes and team strategies.', 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=60', 'ACTIVE'),
('League of Legends', 'Team-based strategy game where two teams of five powerful champions face off.', 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=60', 'ACTIVE'),
('Rocket League', 'High-powered hybrid of arcade-style soccer and vehicular mayhem.', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=60', 'ACTIVE');
